Fixes #15901: Ununderstandable error messages when server is not up and agent is installed

diff --git a/share/commands/agent-inventory b/share/commands/agent-inventory
--- a/share/commands/agent-inventory
+++ b/share/commands/agent-inventory
@@ -31,6 +31,13 @@
 
 bootstrap_check
 
+# We cannnot strart an inventory in bootstrap policies
+if cmp -s "/var/rudder/cfengine-community/inputs/failsafe.cf" "/opt/rudder/share/bootstrap-promises/failsafe.cf"
+then
+  >&2 echo "Agent is currently in bootstrap policies, cannot run an inventory, you need to download initial policies from the server"
+  exit 1
+fi
+
 # Ignore disable-inventory flag
 FORCE=0
 OPTS=""
