Fixes #16825: When a node is in bootstrap mode there is no understandable way to unlock it from this state

diff --git a/share/commands/agent-inventory b/share/commands/agent-inventory
--- a/share/commands/agent-inventory
+++ b/share/commands/agent-inventory
@@ -31,10 +31,10 @@
 
 bootstrap_check
 
-# We cannnot strart an inventory in bootstrap policies
+# We cannnot start an inventory in bootstrap policies
 if cmp -s "/var/rudder/cfengine-community/inputs/failsafe.cf" "/opt/rudder/share/bootstrap-promises/failsafe.cf"
 then
-  >&2 echo "Agent is currently in bootstrap policies, cannot run an inventory, you need to download initial policies from the server"
+  >&2 echo "Agent is currently in bootstrap policies, cannot run an inventory. Please download initial policies from the server with command `rudder agent update` first. If problem persists, use `rudder agent check` for diagnostic"
   exit 1
 fi
 
